services:
  - type: web
    name: feirinha-api
    runtime: python
    rootDirectory: feirinha-api-clean
    buildCommand: |
      cd feirinha-api-clean && 
      pip install -r requirements.txt
    startCommand: |
      cd feirinha-api-clean && 
      gunicorn src.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.10
