services:
  - type: web
    name: feirinha-api
    runtime: python
    rootDirectory: feirinha-api-clean
    buildCommand: |
      cd feirinha-api-clean && 
      pip install -r requirements.txt
    startCommand: |
      cd feirinha-api-clean && 
      gunicorn src.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      # Adicionar todas as variáveis do .env aqui
      - key: SECRET_KEY
        value: dev-key-123
      - key: DEBUG
        value: "true"
      - key: GCP_TYPE
        value: service_account
      - key: GCP_PROJECT_ID
        value: steel-flare-462801-e2
      # ... adicionar todas as outras variáveis do Google
      - key: SPREADSHEET_ID
        value: 1SBvTUfk0sQ3Fp_dXRa5GbCYccVbglKaww-R8BgiOk7M
