services:
  - type: web
    name: feirinha-api
    runtime: python
    rootDirectory: feirinha-api-clean
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.10
